server.port=8083
spring.application.name=appointment-service

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/appointment_service_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# OpenFeign Logging (Optional)
logging.level.com.healthcare.appointmentservice.client=DEBUG

# PayHere Credentials
payhere.merchant.id=${PAYHERE_MERCHANT_ID:1232121}
payhere.merchant.secret=${PAYHERE_MERCHANT_SECRET:MTM2ODU5NDI3NjE0MjUxMzU0NDg1MDk1OTEyNDgzOTcyMzA3ODQw}
