apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
        - name: appointment-service
          image: healthcare/appointment-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://healthcare-db:5432/appointment_service_db
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: healthcare-platform-config
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: healthcare-platform-config
                  key: POSTGRES_PASSWORD
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: PAYHERE_MERCHANT_ID
              valueFrom:
                configMapKeyRef:
                  name: healthcare-platform-config
                  key: PAYHERE_MERCHANT_ID
            - name: PAYHERE_MERCHANT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: healthcare-platform-config
                  key: PAYHERE_MERCHANT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: appointment-service
spec:
  selector:
    app: appointment-service
  ports:
    - port: 8083
      targetPort: 8083
