apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: healthcare/notification-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8088
          env:
            - name: SPRING_MAIL_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: healthcare-platform-config
                  key: SPRING_MAIL_USERNAME
            - name: SPRING_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: healthcare-platform-secrets
                  key: SPRING_MAIL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - port: 8088
      targetPort: 8088
