apiVersion: v1
kind: ConfigMap
metadata:
  name: healthcare-platform-config
data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  AUTH_DB: auth_service_db
  DOCTOR_DB: doctor_service_db
  APPOINTMENT_DB: appointment_service_db
  PATIENT_DB: patient_service_db
  PAYHERE_MERCHANT_ID: "1232121"
  PAYHERE_MERCHANT_SECRET: "MTM2ODU5NDI3NjE0MjUxMzU0NDg1MDk1OTEyNDgzOTcyMzA3ODQw"
  JITSI_ROOM_SECRET: ravvycare-secure-secret-2026
