apiVersion: v1
kind: ConfigMap
metadata:
  name: healthcare-platform-config
data:
  SPRING_DATASOURCE_USERNAME: "postgres"
  PAYHERE_MERCHANT_ID: "1232121"
  JITSI_ROOM_SECRET: "ravvycare-secure-secret-2026"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_GENERATE_DDL: "true"
  SPRING_MAIL_USERNAME: "ravindusdc@gmail.com"
