apiVersion: v1
kind: ConfigMap
metadata:
  name: healthcare-db-init
data:
  init-db.sql: |
    CREATE DATABASE auth_service_db;
    CREATE DATABASE doctor_service_db;
    CREATE DATABASE appointment_service_db;
    CREATE DATABASE patient_service_db;
